export { default as Navigation } from "./Navigation";
export { default as HeroSection } from "./HeroSection";
export { default as AboutSection } from "./AboutSection";
export { default as ProjectsSection } from "./ProjectsSection";
export { default as ServicesSection } from "./ServicesSection";
export { default as ContactSection } from "./ContactSection";
export { default as Footer } from "./Footer";
export { default as ProjectModal } from "./ProjectModal";
export { default as GlobalEffects } from "./GlobalEffects";
