-- Add full customization columns to Settings table
-- Branding
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "logoWidth" INTEGER DEFAULT 40;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "logoHeight" INTEGER DEFAULT 40;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "faviconUrl" TEXT;

-- Typography - Headings
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "headingFont" TEXT DEFAULT 'system-ui';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "headingWeight" TEXT DEFAULT '300';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "headingColor" TEXT DEFAULT '#242222';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "headingColorDark" TEXT DEFAULT '#FFFFFF';

-- Typography - Body
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "bodyFont" TEXT DEFAULT 'system-ui';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "bodyWeight" TEXT DEFAULT '400';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "bodySize" TEXT DEFAULT '16px';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "bodyColor" TEXT DEFAULT '#242222';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "bodyColorDark" TEXT DEFAULT '#FFFFFF';

-- Typography - Nav
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "navFont" TEXT DEFAULT 'system-ui';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "navWeight" TEXT DEFAULT '500';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "navSize" TEXT DEFAULT '12px';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "navLetterSpacing" TEXT DEFAULT '0.1em';

-- Hero sizing
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "heroTitleSize" TEXT DEFAULT '8xl';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "heroSubtitleSize" TEXT DEFAULT 'lg';

-- Additional colors
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "secondaryColor" TEXT DEFAULT '#c8ff00';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "accentColor" TEXT DEFAULT '#BBFF00';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "darkText" TEXT DEFAULT '#242222';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "lightText" TEXT DEFAULT '#FFFFFF';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "mutedText" TEXT DEFAULT '#B8B8B8';

-- Buttons
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "buttonBg" TEXT DEFAULT '#BBFF00';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "buttonText" TEXT DEFAULT '#242222';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "buttonHoverBg" TEXT DEFAULT '#242222';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "buttonHoverText" TEXT DEFAULT '#BBFF00';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "buttonRadius" TEXT DEFAULT '0px';

-- Effects
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "enableGrain" BOOLEAN DEFAULT true;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "enableCursor" BOOLEAN DEFAULT true;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "enableAnimations" BOOLEAN DEFAULT true;
